new version build

diff --git a/.github/workflows/ami_build.yml b/.github/workflows/ami_build.yml
--- a/.github/workflows/ami_build.yml
+++ b/.github/workflows/ami_build.yml
@@ -2,7 +2,7 @@ name: AMI build
 
 on:
   push:
-    branches: [temp]
+    branches: [main]
 
 jobs:
   connect-remote:
@@ -48,3 +48,13 @@ jobs:
       - name: Refresh autoscaling group
         run: |
           aws autoscaling start-instance-refresh --auto-scaling-group-name ${{ secrets.AUTOSCALING_GROUP }}
+          status=""
+          while [[ $status != "Successful" && $status != "Failed" ]]; do
+            sleep 60
+            status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name ${{ secrets.AUTOSCALING_GROUP }} --query 'InstanceRefreshes[0].Status' --output text)
+          done
+          echo "Instance refresh status: $status"
+          if [ $status == "Failed" ]; then
+            echo "Instance refresh failed. Exiting with an error."
+            exit 1
+          fi
